# Generated by Django 4.1.5 on 2023-02-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.ImageField(default='aaa', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
